### ISSUE TITLE
Building from source error

### ISSUE THREAD

**Issue by PrakharSaxena24** [NeuroQuestAi/five-factor-e#17]
Hey, thank you for the work! 

I tried to build from source and got error, I tried it on two seperate machines (Linux and Mac m2). 

Error stack on mac - 
```
(henry) tanakai@Tanakas-MacBook-Pro five-factor-e % pip install -e .
Obtaining file:///Users/tanakai/Upwork/five-factor-e
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting black<24.0.0,>=23.9.1 (from five-factor-e==1.11.1)
  Downloading black-23.12.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (68 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 kB 5.8 MB/s eta 0:00:00
Collecting coverage<8.0.0,>=7.3.1 (from five-factor-e==1.11.1)
  Downloading coverage-7.5.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (8.2 kB)
Collecting isort<6.0.0,>=5.12.0 (from five-factor-e==1.11.1)
  Downloading isort-5.13.2-py3-none-any.whl.metadata (12 kB)
Collecting plotext<6.0.0,>=5.2.8 (from five-factor-e==1.11.1)
  Downloading plotext-5.2.8-py3-none-any.whl.metadata (5.3 kB)
Collecting click>=8.0.0 (from black<24.0.0,>=23.9.1->five-factor-e==1.11.1)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting mypy-extensions>=0.4.3 (from black<24.0.0,>=23.9.1->five-factor-e==1.11.1)
  Downloading mypy_extensions-1.0.0-py3-none-any.whl.metadata (1.1 kB)
Collecting packaging>=22.0 (from black<24.0.0,>=23.9.1->five-factor-e==1.11.1)
  Using cached packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: pathspec>=0.9.0 in /Users/tanakai/miniconda3/envs/henry/lib/python3.11/site-packages (from black<24.0.0,>=23.9.1->five-factor-e==1.11.1) (0.12.1)
Collecting platformdirs>=2 (from black<24.0.0,>=23.9.1->five-factor-e==1.11.1)
  Downloading platformdirs-4.2.2-py3-none-any.whl.metadata (11 kB)
Downloading black-23.12.1-cp311-cp311-macosx_11_0_arm64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 6.4 MB/s eta 0:00:00
Downloading coverage-7.5.2-cp311-cp311-macosx_11_0_arm64.whl (204 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.8/204.8 kB 11.7 MB/s eta 0:00:00
Downloading isort-5.13.2-py3-none-any.whl (92 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.3/92.3 kB 8.2 MB/s eta 0:00:00
Downloading plotext-5.2.8-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.2/60.2 kB 6.3 MB/s eta 0:00:00
Downloading click-8.1.7-py3-none-any.whl (97 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 8.0 MB/s eta 0:00:00
Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Using cached packaging-24.0-py3-none-any.whl (53 kB)
Downloading platformdirs-4.2.2-py3-none-any.whl (18 kB)
Building wheels for collected packages: five-factor-e
  Building editable for five-factor-e (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building editable for five-factor-e (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Traceback (most recent call last):
        File "/Users/tanakai/miniconda3/envs/henry/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/tanakai/miniconda3/envs/henry/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/tanakai/miniconda3/envs/henry/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 273, in build_editable
          return hook(wheel_directory, config_settings, metadata_directory)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8n/895p8lvs5tq4_c66dfxw7g8r0000gn/T/pip-build-env-2oihg7cr/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 82, in build_editable
          return WheelBuilder.make_in(
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8n/895p8lvs5tq4_c66dfxw7g8r0000gn/T/pip-build-env-2oihg7cr/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 88, in make_in
          wb.build(target_dir=directory)
        File "/private/var/folders/8n/895p8lvs5tq4_c66dfxw7g8r0000gn/T/pip-build-env-2oihg7cr/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 118, in build
          self._add_pth(zip_file)
        File "/private/var/folders/8n/895p8lvs5tq4_c66dfxw7g8r0000gn/T/pip-build-env-2oihg7cr/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 147, in _add_pth
          for include in self._module.includes:
                         ^^^^^^^^^^^^
        File "/Users/tanakai/miniconda3/envs/henry/lib/python3.11/functools.py", line 1001, in __get__
          val = self.func(instance)
                ^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8n/895p8lvs5tq4_c66dfxw7g8r0000gn/T/pip-build-env-2oihg7cr/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/builder.py", line 97, in _module
          return Module(
                 ^^^^^^^
        File "/private/var/folders/8n/895p8lvs5tq4_c66dfxw7g8r0000gn/T/pip-build-env-2oihg7cr/overlay/lib/python3.11/site-packages/poetry/core/masonry/utils/module.py", line 75, in __init__
          PackageInclude(
        File "/private/var/folders/8n/895p8lvs5tq4_c66dfxw7g8r0000gn/T/pip-build-env-2oihg7cr/overlay/lib/python3.11/site-packages/poetry/core/masonry/utils/package_include.py", line 31, in __init__
          self.check_elements()
        File "/private/var/folders/8n/895p8lvs5tq4_c66dfxw7g8r0000gn/T/pip-build-env-2oihg7cr/overlay/lib/python3.11/site-packages/poetry/core/masonry/utils/package_include.py", line 72, in check_elements
          raise ValueError(
      ValueError: /Users/tanakai/Upwork/five-factor-e/five_factor_e does not contain any element
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for five-factor-e
Failed to build five-factor-e
ERROR: Could not build wheels for five-factor-e, which is required to install pyproject.toml-based projects
```

**Comment by edersoncorbari** [comment]
Hi @PrakharSaxena24 

It might be something related to Poetry.

Try the following commands:

`poetry shell
`

`
mkdir five_factor_e ; touch five_factor_e/__init__.py ; pip install -e .
`

![here](https://github.com/user-attachments/assets/77fbd8e4-2ca1-4b21-9f49-93f8404d7ab9)

Cheers,
EDMC.
